spring:
  data:
    mongodb:
      host: localhost
      port: 0 # For SpringBootTest, MongoDataTest. Each of these are running embedded MongoDB.
      database: test

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.0